### ISSUE TITLE
Missing module graphrust declared in lib.rs

### ISSUE THREAD

**Issue by GauvainD** [umons-dept-comp-sci/PhoegRustGraph#13]
I temporarily commented out the line in lib.rs until we know what this file is and what it contains.

**Comment by antegallya** [comment]
This is 11 months old and nothing has resurfaced concerning it. I guess we can safely remove and close this issue ?

**Comment by GauvainD** [comment]
I guess it was a problem with some automated refactoring. The graphrust module does not exist, and no file was deleted.
